name: CI/CD Pipeline
on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  CI-Jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run first test script
        run: python test-script/demo-test-1.py

      - name: Run second test script
        run: python test-script/demo-test-2.py

  deploy:
    needs: CI-Jobs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.6.0"

      - name: Initialize Terraform
        run: terraform init
        working-directory: .

      - name: Plan Terraform Deployment
        run: terraform plan -out=tfplan
        working-directory: .

      - name: Apply Terraform Deployment
        run: terraform apply -auto-approve tfplan
        working-directory: .


